kind: pipeline
name: default

steps:
- name: test
  image: ubuntu
  commands:
  - ./atmos.py --help
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    repo: spengreb/test-container
    tags: latest